plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.99'
    id 'idea'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG

            systemProperty 'mixin.env.remapRefMap', 'true'
            systemProperty 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
        }

        client {
            client()
            gameDirectory = project.file("run/${minecraft_version}/run-client")
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            gameDirectory = project.file("run/${minecraft_version}/run-server")
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            gameDirectory = project.file("run/${minecraft_version}/run-gametestserver")
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        data {
            data()
            gameDirectory = project.file("run/${minecraft_version}/run-data")
            programArguments.addAll '--all', '--mod', project.mod_id, '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath(), '--existing-mod', 'create', '--existing-mod', 'gtceu'
        }
    }
    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

repositories {
    mavenCentral()
    maven { url = 'https://mvn.devos.one/snapshots/'
        content {
            includeGroup "com.tterrag.registrate"
        }
    }
    maven { url = 'https://maven.createmod.net'
        content {
            includeGroup "net.createmod.ponder"
            includeGroup "dev.engine-room.flywheel"
            includeGroup "com.simibubi.create"
        }
    }
    maven { url = 'https://maven.blamejared.com'
        content {
            includeGroup "mezz.jei"
        }
    }
    maven { url = 'https://maven.shedaniel.me/'
        content {
            includeGroup "dev.architectury"
        }
    }
    maven { url = 'https://maven.latvian.dev/releases'
        content {
            includeGroup 'dev.latvian.mods'
        }
    }
    maven { url = 'https://cursemaven.com'
        content {
            includeGroup "curse.maven"
        }
    }
    maven { url = 'https://maven.firstdarkdev.xyz/snapshots'
        content {
            includeGroup 'com.lowdragmc.ldlib'
        }
    }
    maven { url = 'https://api.repsy.io/mvn/toma/public/'
        content {
            includeGroup 'dev.toma.configuration'
        }
    }
    maven { url = 'https://maven.gtceu.com'
        content {
            includeGroup 'com.gregtechceu.gtceu'
        }
    }
    maven { url = 'https://maven.parchmentmc.org' }
    maven { url = 'https://maven.neoforged.net/releases' }
    maven { url = 'https://maven.quiltmc.org/repository/release/' }
}

dependencies {
    implementation ("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
    implementation "net.createmod.ponder:Ponder-NeoForge-${minecraft_version}:${ponder_version}"
    compileOnly "dev.engine-room.flywheel:flywheel-neoforge-api-${minecraft_version}:${flywheel_version}"
    runtimeOnly "dev.engine-room.flywheel:flywheel-neoforge-${minecraft_version}:${flywheel_version}"
    implementation "com.tterrag.registrate:Registrate:${registrate_version}"

    compileOnly ("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}") { transitive = false }
    compileOnly ("mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}") { transitive = false }
    runtimeOnly ("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}") { transitive = false }

    implementation "dev.architectury:architectury-neoforge:${architectury_version}"
    implementation "dev.latvian.mods:rhino:${rhino_version}"
    implementation ("dev.latvian.mods:kubejs-neoforge:${kubejs_version}") {transitive = false }
    //compileOnly ("dev.latvian.mods:kubejs-create-neoforge:${kubejs_create_version}") { transitive = false }

    implementation ("com.lowdragmc.ldlib:ldlib-neoforge-${minecraft_version}:${ldlib_version}") { transitive = false }
    implementation ("com.gregtechceu.gtceu:gtceu-${minecraft_version}:${gregtech_version}") { transitive = false }
    implementation "dev.toma.configuration:configuration-${minecraft_version}:${configuration_version}"

    implementation "curse.maven:jade-324717:${jade_version}"
    runtimeOnly "curse.maven:spark-361579:${spark_version}"

    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:${mixin_extras_version}"))
    implementation "io.github.llamalad7:mixinextras-neoforge:${mixin_extras_version}"
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_verison: minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version: neo_version,
            loader_version_range: loader_version_range,
            mod_id: mod_id,
            mod_name: mod_name,
            mod_license: mod_license,
            mod_version: mod_version,
            mod_authors: mod_authors,
            mod_description: mod_description,
            create_version_range: create_version_range,
            gregtech_version_range: gregtech_version_range
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generates/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
