org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21
parchment_mappings_version=2024.11.10

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.152
loader_version_range=[1,)

mod_id=greate
mod_name=Greate
mod_license=MIT
mod_version=0.0.46
mod_group_id=electrolyte.greate
mod_authors=Electrolyte, lonevox
mod_description=Create Gregified

mixin_extras_version=0.5.0-rc.3
create_version=6.0.6-99
create_version_range=[6.0.6,)
ponder_version=1.0.59
flywheel_version=1.0.4
registrate_version=MC1.21-1.3.0+67
jei_version=19.21.2.313
kubejs_version=2101.7.1-build.181
#kubejs_create_version=2001.3.0-build.8
rhino_version=2101.2.7-build.74
architectury_version=13.0.8
ldlib_version=1.0.35.a
configuration_version=3.1.0-neoforge
gregtech_version=7.0.2
gregtech_version_range=[7.0.1,)
jade_version=6738687
spark_version=6225208