# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx1G

minecraft_version=1.20.1
forge_version=47.4.0
parchment_version=2023.09.03
mixin_extras_version=0.5.0-rc.3
greate_version=0.0.52
create_version=6.0.6-141
ponder_version=1.0.81
flywheel_version=1.0.4
registrate_version=MC1.20-1.3.11
jei_version=15.20.0.105
kubejs_version=2001.6.5-build.16
kubejs_create_version=2001.3.0-build.8
rhino_version=2001.2.3-build.10
architectury_version=9.2.14
ldlib_version=1.0.40.b
configuration_version=2.2.0
gregtech_version=7.2.0
jade_version=4801177
spark_version=4738952