modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/GreateBeyondTheHorizon/Greate/issues"

[[mods]]
modId="greate"
version="0.0.5"
displayName="Greate"
displayURL="https://modrinth.com/mod/greate"
#logoFile="examplemod.png"
credits="Both the Create & Gregtech devs for making awesome mods!"
authors="Electrolyte"

description="Create Gregified"

[[dependencies.greate]]
    modId="kubejs_create"
    mandatory=false
    versionRange="[1902.2.4-build.29,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.greate]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.c,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.greate]]
    modId="gtceu"
    mandatory=true
    versionRange="[1.0.11.b,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.greate]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.greate]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
