modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/GreateBeyondTheHorizon/Greate/issues"

[[mods]]
modId="greate"
version="${file.jarVersion}"
displayName="Greate"
displayURL="https://modrinth.com/mod/greate"
logoFile="logo.png"
credits="Both the Create & Gregtech devs for making awesome mods!"
authors="Electrolyte"

description="Create Gregified"

[[dependencies.greate]]
    modId="kubejs_create"
    mandatory=true
    versionRange="[2001.2.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.greate]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.e,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.greate]]
    modId="gtceu"
    mandatory=true
    versionRange="[1.1.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.greate]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.greate]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
