modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL="https://github.com/GreateBeyondTheHorizon/Greate/issues"

[[mods]]
modId="greate"
version="${file.jarVersion}"
displayName="Greate"
displayURL="https://modrinth.com/mod/greate"
#logoFile="examplemod.png"
credits="Both the Create & Gregtech devs for making awesome mods!"
authors="Electrolyte"

description="Create Gregified"

[[dependencies.greate]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.c,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.greate]]
    modId="gtceu"
    mandatory=true
    versionRange="[1.0.10,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.greate]]
    modId="configuration"
    mandatory=true
    versionRange="[2.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.greate]]
    modId="forge"
    mandatory=true
    versionRange="[43.2.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.greate]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"
