name: Create Release

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  RELEASE_VERSION: 0.0.15

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'forge-1.20.1'
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build
      uses: gradle/gradle-build-action@v2.4.2
      with:
          cache-read-only: false
          arguments: build
    - name: Upload Release to Github & Modrinth
      uses: Kir-Antipov/mc-publish@v3.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        github-tag: ${{ env.RELEASE_VERSION }}-forge
        github-generate-changelog: false
        github-prerelease: true

        name: Greate ${{ env.RELEASE_VERSION }} [FORGE]
        version: ${{ env.RELEASE_VERSION }}
        changelog-file: changelog.md

        modrinth-id: 8wDcQuht
        modrinth-featured: true
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        version-type: alpha

        loaders: |
          forge
          neoforge

        game-versions: |
          1.20.1

        dependencies: |
          create(required)
          gregtechceu-modern(required)
          kubejs-create(required)

        files: |
          build/libs/*[0-9].jar
       
